In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.
l=[0,1,2,3,4,5]
arr = np.array(l)
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
# 2.  Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5,2.6,3.7])
print(arr.dtype == np.float64)

True


In [ ]:
# 3.Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
l=[1+2j,3+5j,8+9j]
arr = np.array(l)
print(arr.dtype)

complex128


In [ ]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr = np.array([1,2,3,4,5,6],dtype=np.float32)
print(arr.dtype)


float32


In [ ]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1.2345234564636,2.452345673456769,4.2456783456789])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr)
print(arr.dtype)

float64
[1.2345234 2.4523456 4.2456784]
float32


In [ ]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type
def array_attributes(arr):
  return arr.shape,arr.size,arr.dtype
arr= np.asarray([5,6,7,8,9,10])
shape,size,data_type= array_attributes(arr)
print("Shape :",shape)
print("Size :",size)
print("Data type :",data_type)

Shape : (6,)
Size : 6
Data type : int64


In [ ]:
# 7.Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.
def array_dimension(arr):
  return arr.ndim
arr= np.asarray([10,11,12,13,14,15,16])
print("The dimension :",array_dimension(arr))


The dimension : 1


In [ ]:
#8.Design a function item_size_info that takes a NumPy array as input and returns the item size and total size in bytes
def item_size_info(arr):
  return arr.itemsize,arr.nbytes
arr=np.asarray([21,22,2,3,13])

item_size,total_bytes = item_size_info(arr)

print("Item size :",item_size)
print("Total_bytes :",total_bytes)




Item size : 8
Total_bytes : 40


In [ ]:
# 9.Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
  return arr.strides
arr = np.asarray([[1,2,3,4,5],[6,7,8,9,10]])
strides = array_strides(arr)
print("The array strides :",strides)

The array strides : (40, 8)


In [ ]:
#10.Design a function shape_stride_relationship that takes a NumPy array as input and returns
# the shape and strides of the array.
def shape_stride_relationship(arr):
  return arr.shape,arr.size
arr = np.asarray([[1,2,3,4,5],[6,7,8,9,10]])
shape,size = shape_stride_relationship(arr)
print("The Shape :",shape)
print("The Size :",size)

The Shape : (2, 5)
The Size : 10


In [ ]:
# 11.Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
# zeros with `n` elements.

def create_zeros_array(n):
  arr=np.zeros(n)
  return arr
n=int(input("Enter n :"))
arr = create_zeros_array(n)
print(arr)

Enter n :7
[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
 # 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
# NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(rows,cols):
  return np.ones((rows,cols))

rows=int(input("Enter the number of rows :"))
cols=int(input("Enter the number of cols :"))

print(create_ones_matrix(rows,cols))

Enter the number of rows :3
Enter the number of cols :3
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 13.  Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

def generate_range_array(start,end,step):
  return np.arange(start,end,step)
start=int(input("Enter start number :"))
end = int(input("Enter end number :"))
step =int(input("Enter step number :"))

arr= generate_range_array(start,end,step)
print(arr)

Enter start number :3
Enter end number :30
Enter step number :4
[ 3  7 11 15 19 23 27]


In [ ]:
# 14.Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
def generate_linear_space(start,stop,num):
  return np.linspace(start,stop,num)
start =float(input("Enter start :"))
stop =float(input("Enter stop :"))
num =int(input("Enter num :"))

print(generate_linear_space(start,stop,num))

Enter start :1
Enter stop :10
Enter num :4
[ 1.  4.  7. 10.]


In [ ]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
# identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):
  return np.eye(n)
n=int(input("Enter n :"))
print(create_identity_matrix(n))

Enter n :5
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.
def list_to_numpy(l):
  return np.array(l)
l =[1,10,21,23,56,7,12,65]
numpy_array= list_to_numpy(l)
print("Numpy array :",numpy_array)
print(type(numpy_array))

Numpy array : [ 1 10 21 23 56  7 12 65]
<class 'numpy.ndarray'>


In [ ]:
# 17.Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
arr=np.array([1,2,3,90,45,6,3])
view = arr.view()

print(arr[0])

view[0]=1000
print(view[0])
print(arr[0])

1
1000
1000


In [ ]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis
def array_concatenates(ones,zeros):
  return np.concatenate((ones,zeros),axis=0) , np.concatenate((ones,zeros),axis=1)
ones = np.ones((3,3))
zeros = np.zeros((3,3))
print("Ones :",ones)
print("Zeros :",zeros)

axis_0 , axis_1 = array_concatenates(ones,zeros)

print("axis = 0 :")
print(axis_0)
print("axis = 1 :")
print(axis_1)

Ones : [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Zeros : [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
axis = 0 :
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
axis = 1 :
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [ ]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
def array_concatenates(ones,zeros):
  return np.concatenate((ones,zeros),axis=0)
ones = np.ones((3,3))
zeros = np.zeros((3,3))
print("Ones :")
print(ones)
print("Zeros :")
print(zeros)

axis_0 = array_concatenates(ones,zeros)

print("Concates Horizontally :")
print(axis_0)


Ones :
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Zeros :
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Concates Horizontally :
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 20.Write a function that vertically stacks multiple NumPy arrays given as a list.
def numpy_stacks(l1,l2,l3):
  return np.vstack([l1,l2,l3])

l1=[1,2,3]
l2=[4,5,6]
l3=[7,8,9]
print("The vertical array stack :")
print(numpy_stacks(l1,l2,l3))

The vertical array stack :
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
# with a given step size.

def generate_array(start,stop,step):
  if (stop-start)% step==0:
    return np.arange(start,stop+step,step)
  else:
    return np.arange(start,stop,step)


start =int(input("Enter start :"))
stop =int(input("Enter stop :"))
step =int(input("Enter step :"))

print(generate_array(start,stop,step))

Enter start :2
Enter stop :20
Enter step :2
[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
# 22.Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def function():
  print(np.linspace(0,1,10))
function()

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#23.Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000
# (inclusive).

def function():
  return np.logspace(0,3,5)
print(function())

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
# 24. . Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
# are random integers between 1 and 100.
arr=np.random.randint(1,100,(5,3))
print(type(arr))

data_frame = pd.DataFrame(arr)
print(data_frame)
print(type(data_frame))

<class 'numpy.ndarray'>
    0   1   2
0  75  26  91
1   4  96  88
2  86  93   7
3  47  16  40
4  92  65  52
<class 'pandas.core.frame.DataFrame'>


In [ ]:
# 25. . Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
# with zeros. Use NumPy operations within the Pandas DataFrame
def neg_to_zero(df,column):
  df[column] = np.where(df[column]<0 ,0,df[column])
  return df
data = {'A': [10, -5, 20, -3, 30], 'B': [-1, 2, -3, 4, 5]}
df=pd.DataFrame(data)
print("Before the operation ")
print(df)

df=neg_to_zero(df,'A')
print("After the data frame ")
print(df)




Before the operation 
    A  B
0  10 -1
1  -5  2
2  20 -3
3  -3  4
4  30  5
After the data frame 
    A  B
0  10 -1
1   0  2
2  20 -3
3   0  4
4  30  5


In [ ]:
# 26.Access the 3rd element from the given NumPy array
arr = np.array([10, 20, 30, 40, 50])

print("The third element is :",arr[2])

The third element is : 30


In [ ]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(arr_2d[1][2])

6


In [ ]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])
arr[arr>5]

array([ 8, 10,  7])

In [ ]:
# 29.  Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])

[3 4 5 6]


In [ ]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(arr_2d[0:2,1:3])

[[2 3]
 [5 6]]


In [ ]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
# provided in another array.

def extract_elements(arr,indexes):
  return arr.flatten()[indexes]
arr = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
indexes = [1,3,5]
result = extract_elements(arr,indexes)
print(result)

[2 4 6]


In [ ]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
# boolean indexing.

def numpy_function(arr,threshold):
  return arr[arr>threshold]
arr=np.array([1,4,56,2,4,254,7,9,534,5,133,44,5,90])
threshold=int(input("Enter threshold :"))
print(numpy_function(arr,threshold))

Enter threshold :23
[ 56 254 534 133  44  90]


In [ ]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
# separate arrays for each dimension.
def extract_elements_3d(arr, row_indices, col_indices, depth_indices):
    return arr[row_indices, col_indices, depth_indices]

arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])

row_indices = [0, 1]
col_indices = [0, 1]
depth_indices = [2, 1]

result = extract_elements_3d(arr, row_indices, col_indices, depth_indices)

print("Extracted elements:", result)


Extracted elements: [ 3 11]


In [ ]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
# using boolean indexing.

def numpy_function(arr):
  return arr[(arr>1) & (arr<100)]
arr=np.array([1,4,56,2,4,254,7,9,534,5,133,44,5,90])
print(numpy_function(arr))

[ 4 56  2  4  7  9  5 44  5 90]


In [ ]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
# in separate arrays.

def extract(arr,rows,cols):
  return arr[rows,cols]

rows = [0,1,2]
cols = [1,2,0]
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])
print(extract(arr,rows,cols))


[20 60 70]


In [ ]:
# 36.  Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr=np.random.randint(1,20,(3,3))
print(arr)
arr = arr+10
print(arr)

[[ 1  2  6]
 [ 6 12 11]
 [19  4  9]]
[[11 12 16]
 [16 22 21]
 [29 14 19]]


In [ ]:
# 37.Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
# corresponding element in arr1 using NumPy broadcasting.
arr1=np.random.randint(1,10,(1,3))
arr2=np.random.randint(1,20,(3,4))
result = arr1.T  * arr2
print(result)



[[ 32  18  10  30]
 [ 40  55  25  15]
 [ 77  35 133  28]]


In [ ]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
# NumPy broadcasting.
arr1=np.random.randint(1,10,(1,4))
arr2=np.random.randint(1,20,(4,3))
print("arr1 :")
print(arr1)
print("arr2 :")
print(arr2)
result = arr1[:,:3] + arr2
print("Result :")
print(result)


arr1 :
[[3 8 8 1]]
arr2 :
[[15 19 13]
 [ 3  5 15]
 [ 7 11 12]
 [ 6  5  3]]
Result :
[[18 27 21]
 [ 6 13 23]
 [10 19 20]
 [ 9 13 11]]


In [ ]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1=np.random.randint(1,10,(3,1))
arr2=np.random.randint(1,10,(1,3))
print("arr1 :")
print(arr1)
print("arr2 :")
print(arr2)
result = arr1 + arr2
print("Result :")
print(result)



arr1 :
[[7]
 [9]
 [5]]
arr2 :
[[7 1 8]]
Result :
[[14  8 15]
 [16 10 17]
 [12  6 13]]


In [ ]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
# broadcasting. Handle the shape incompatibility.
arr1=np.random.randint(1,10,(2,3))
arr2=np.random.randint(1,10,(2,2))
print("arr1 :")
print(arr1)
print("arr2 :")
print(arr2)
result = arr1[:,:2] * arr2
print("Result :")
print(result)


arr1 :
[[2 5 5]
 [8 1 1]]
arr2 :
[[5 3]
 [1 4]]
Result :
[[10 15]
 [ 8  4]]


In [ ]:
# 41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("Column wise mean is :",np.mean(arr,axis=0))

[[1 2 3]
 [4 5 6]]
Column wise mean is : [2.5 3.5 4.5]


In [ ]:
# 42.  Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("The maximum value in each row :",np.max(arr,axis=1))

[[1 2 3]
 [4 5 6]]
The maximum value in each row : [3 6]


In [ ]:
# 43.  For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:")
print(arr)

col_max_indexes = np.argmax(arr,axis=0)
print("indices of maximum value in each column :",col_max_indexes)

Array:
[[1 2 3]
 [4 5 6]]
indices of maximum value in each column : [1 1 1]


In [ ]:
# 44.For the given array, apply custom function to calculate moving sum along rows

def custom_sum(arr,window_size=2):
  result=[]
  for row in arr:
    row_sum = [sum(row[i:i+window_size]) for i in range(len(row) -window_size+1)]
    result.append(row_sum)
  return result


arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:")
print(arr)

print("sum along rows :", custom_sum(arr))



Array:
[[1 2 3]
 [4 5 6]]
sum along rows : [[3, 5], [9, 11]]


In [ ]:
# 45.In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])

result = np.all(arr%2==0, axis =0)
print("Result :",result)


Result : [False False False]


In [ ]:
# 46.Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
# reshaped matrix.

original_array = np.array([1, 2, 3, 4, 5, 6])
print("Original_array :",original_array)
print("Reshaped Matrix :")
print(original_array.reshape(2,3))

Original_array : [1 2 3 4 5 6]
Reshaped Matrix :
[[1 2 3]
 [4 5 6]]


In [ ]:
# 47.Create a function that takes a matrix as input and returns the flattened array

def flatten(arr):
  return arr.flatten()
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("The original array :")
print(input_matrix)

print("Flatten array :", flatten(input_matrix))

The original array :
[[1 2 3]
 [4 5 6]]
Flatten array : [1 2 3 4 5 6]


In [ ]:
# 48. Write a function that concatenates two given arrays along a specified axis.

def concatenates(arr1 ,arr2,axis):
  return np.concatenate((arr1,arr2),axis=axis)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print("concatenates with axis_0")
print(concatenates(array1,array2,0))

print("concatenates with axis_1")
print(concatenates(array1,array2,1))


concatenates with axis_0
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenates with axis_1
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.

def split(arr,num_splits,axis):
  return np.array_split(arr,num_splits,axis=axis)
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("original_array :")
print(original_array)
num_splits=int(input("Enter thr number of splits :"))
array_split_axis_0 =split(original_array,num_splits,0)
print("Array split with axis 0 :")
for sub_arr in array_split_axis_0:
  print(sub_arr)
array_split_axis_1 =split(original_array,num_splits,1)
print("Array split with axis 1 :")
for sub_arr in array_split_axis_1:
  print(sub_arr)


original_array :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Enter thr number of splits :3
Array split with axis 0 :
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]
Array split with axis 1 :
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [ ]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
def update(arr,indices_to_insert,values_to_insert,indices_to_delete):
  arr = np.insert(arr,indices_to_insert,values_to_insert)
  arr =np.delete(arr,indices_to_delete)
  return arr
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
updated_array= update(original_array,indices_to_insert,values_to_insert,indices_to_delete)
print("Original_array :",original_array)
print("Updated_array :",updated_array)

Original_array : [1 2 3 4 5]
Updated_array : [ 1 10  4 11  5]


In [ ]:
# 51.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
# Perform element-wise addition between `arr1` and `arr2`.
arr1 = np.random.randint(11,100,size=10)
print("Array 1 :",arr1)
arr2= np.arange(1,11)
print("Array 2 :",arr2)
print("Element-wise addition :")
print(arr1+arr2)


Array 1 : [50 92 45 49 16 19 88 19 85 40]
Array 2 : [ 1  2  3  4  5  6  7  8  9 10]
Element-wise addition :
[51 94 48 53 21 25 95 27 94 50]


In [ ]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
# from 1 to 10. Subtract `arr2` from `arr1` element-wise.
arr1 =np.arange(10,0,-1)
print("Array 1 :",arr1)
arr2= np.arange(1,11)
print("Array 2 :",arr2)
print("Element-wise subraction :")
print(arr1-arr2)





Array 1 : [10  9  8  7  6  5  4  3  2  1]
Array 2 : [ 1  2  3  4  5  6  7  8  9 10]
Element-wise subraction :
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
# Perform element-wise multiplication between `arr1` and `arr2`.

arr1 = np.random.randint(6,20,size=5)
print("Array 1 :",arr1)
arr2= np.arange(1,6)
print("Array 2 :",arr2)
print("Element-wise multiplication :")
print(arr1*arr2)


Array 1 : [16 19 19  6 14]
Array 2 : [1 2 3 4 5]
Element-wise multiplication :
[16 38 57 24 70]


In [ ]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
# to 5. Perform element-wise division of `arr1` by `arr2`.
arr1 = np.arange(2,11,2)
print("Array 1 :",arr1)
arr2= np.arange(1,6)
print("Array 2 :",arr2)
print("Element-wise multiplication :")
print(arr1*arr2)


Array 1 : [ 2  4  6  8 10]
Array 2 : [1 2 3 4 5]
Element-wise multiplication :
[ 2  8 18 32 50]


In [ ]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
# reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

arr1 = np.arange(1,6)
print("Array 1 :",arr1)
arr2= np.arange(5,0,-1)
print("Array 2 :",arr2)
print("Exponentiation of `arr1` raised to the power of `arr2`")
print(arr1**arr2)


Array 1 : [1 2 3 4 5]
Array 2 : [5 4 3 2 1]
Exponentiation of `arr1` raised to the power of `arr2`
[ 1 16 27 16  5]


In [ ]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
def count(arr,substring):
  return np.char.count(arr,substring)

arr = np.array(["apple banana", "banana apple", "cherry apple banana", "apple pie", "grape"])
substring = "apple"
result = count(arr,substring)
print(result)

[1 1 1 1 0]


In [ ]:
 # 57. Write a function that extracts uppercase characters from a NumPy array of strings.
def extract(arr):
  return np.array([''.join( char for char in word if char.isupper()) for word in arr])
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
print(extract(arr))

['H' 'W' 'OAI' 'GPT']


In [ ]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
def replace(s,old,new):
  return np.char.replace(s,old,new)
s =["cricket bat","cricket ball","cricket player","cricket ground"]
print("The original array :",s)
print("After replacing :",replace(s,"cricket","hockey"))

The original array : ['cricket bat', 'cricket ball', 'cricket player', 'cricket ground']
After replacing : ['hockey bat' 'hockey ball' 'hockey player' 'hockey ground']


In [ ]:
# 59.Write a function that concatenates strings in a NumPy array element-wise.
def concat(arr1,arr2):
  return np.char.add(arr1,arr2)
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
print("The string concatenate element wise :",concat(arr1,arr2))



The string concatenate element wise : ['HelloOpen' 'WorldAI']


In [ ]:
# 60.Write a function that finds the length of the longest string in a NumPy array.
def length(arr):
  max_length =0
  for i in arr:
    max_length = max(len(i),max_length)
  return max_length
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print("Length of longest string :",length(arr))

Length of longest string : 9


In [ ]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
# standard deviation of the dataset using NumPy's functions.
data = np.random.randint(1,1000,100)
print("Data :",data)
print("Mean :",np.mean(data))
print("Median :",np.median(data))
print("Variance :",np.var(data))
print("Standard Deviation :",np.std(data))



Data : [483 107 992 654 219 304 100 907 667 997  71 737 167 490 334 754 247 611
 532 478 292  31 847  47 218 851 538 358 656 635 835 426 773  81 701 716
  50 300  81 356 133 765 346 722 382 610 291 160 781  57  91 950 929 657
 952 842 795 225 830 249 413 406 148 598 748 212 508 142  62 444 422 621
 624 174 194 193 549 227 259 802 613   9 694 283 897 884 341 401 371 490
 239  17 689 910 808 980 732 830 578 542]
Mean : 484.64
Median : 486.5
Variance : 82286.3504
Standard Deviation : 286.85597501185157


In [ ]:
# 62.Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
data = np.random.randint(1,100,50)
print(data)
percentile_25 = np.percentile(data,25)
percentile_75 = np.percentile(data,75)
print("25th percentile :",percentile_25)
print("75th percentile :",percentile_75)


[31 65  9 94 68 96 20 49 62 24 50 31 35 69 96 37  8 90 47  3 96 32  8 48
 48  4  4 81 71 86  8 31 38 33 61 12 56 87 66 64 87 49 79 44 13 55 85 38
 99 49]
25th percentile : 31.0
75th percentile : 70.5


In [ ]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
# arrays using NumPy's `corrcoef` function.
data1 = np.random.randint(1,100,50)
data2 = np.random.randint(1,100,50)

corelation_matrix = np.corrcoef(data1,data2)

print("Corelation_matrix :")
print(corelation_matrix)
print("Corelation_value :")
print(corelation_matrix[0][1])

Corelation_matrix :
[[1.        0.0408688]
 [0.0408688 1.       ]]
Corelation_value :
0.04086880277385334


In [ ]:
# 64.Create two matrices and perform matrix multiplication using NumPy's `dot` function.
data1 = np.random.randint(1,100,(3,3))
data2 = np.random.randint(1,100,(3,3))
print("Matrix Multiplication")
print(np.dot(data1,data2))

Matrix Multiplication
[[10117 10161  5055]
 [ 7438  8349  4400]
 [ 8182  9242  6042]]


In [ ]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
# percentiles along with the first and third quartiles.
data = np.random.randint(10,1001,50)
data
percentile_10 =np.percentile(data,10)
percentile_25 =np.percentile(data,25)
percentile_50 =np.percentile(data,50)
percentile_75 =np.percentile(data,75)
percentile_90 =np.percentile(data,90)

print("10th percentile :",percentile_10)
print("25th percentile :",percentile_25)
print("50th percentile :",percentile_50)
print("75th percentile :",percentile_75)
print("90th percentile :",percentile_90)

10th percentile : 73.5
25th percentile : 227.25
50th percentile : 432.5
75th percentile : 738.0
90th percentile : 911.1


In [ ]:
# 66. Create a NumPy array of integers and find the index of a specific element.
arr=np.array([1,3,4,567,65,76,3,54,5,6,3])
print("Array :",arr)
element=int(input("Element :"))
index = np.where(arr==element)
print(f"The index of {element} is {index}")

Array : [  1   3   4 567  65  76   3  54   5   6   3]
Element :3
The index of 3 is (array([ 1,  6, 10]),)


In [ ]:
# 67.Generate a random NumPy array and sort it in ascending order
data = np.random.randint(1,100,20)
print(data)
print("Array in asending order :",np.sort(data))

[85 62 50  9 46 14 18 15 80 25 25 75 99  8 66 76 96 94 49  1]
Array in asending order : [ 1  8  9 14 15 18 25 25 46 49 50 62 66 75 76 80 85 94 96 99]


In [ ]:
# 68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
arr[arr>20]

array([25, 42, 30])

In [ ]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
arr[arr%3==0]

array([12, 15])

In [ ]:
# 70.Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

arr[(arr>=20)&(arr<=40)]

array([20, 30, 40])

In [29]:
# 71.For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])
print("The byte order :",arr.dtype.byteorder)

The byte order : =


In [31]:
# 72.For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print(arr)

[16777216 33554432 50331648]


In [34]:
# 73.For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
new_arr =arr.newbyteorder()
print(new_arr)

[16777216 33554432 50331648]


In [38]:
# 74.For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder =="=":
  swapped_arr = arr.newbyteorder()
else:
  swapped_arr = arr
print("Original Array :",arr)
print("Swapped Array :",swapped_arr)
print("Original Array byeteorder :",arr.dtype.byteorder)
print("Swapped Array :",swapped_arr.dtype.byteorder)

Original Array : [1 2 3]
Swapped Array : [16777216 33554432 50331648]
Original Array byeteorder : =
Swapped Array : >


In [40]:
# 75.For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
# attribute `byteorder`.

arr = np.array([1, 2, 3], dtype=np.int32)

if arr.dtype.byteorder =='=':
  print("Byte swap is not necessary")
else:
  print("Byte swap is necessary")

Byte swap is not necessary


In [60]:
# 76.Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
# an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

arr1 = np.arange(1,11)
copy_arr = arr1.copy()
print("Original Array :",arr1)
print("Copy Array :",copy_arr)
copy_arr[0]=1111111
if np.array_equal(arr1,copy_arr):
  print("modifying copy_arr is  affecting arr1")
else:
  print("modifying copy_arr is not affecting arr1")


Original Array : [ 1  2  3  4  5  6  7  8  9 10]
Copy Array : [ 1  2  3  4  5  6  7  8  9 10]
modifying copy_arr is not affecting arr1


In [67]:
# 77.Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

matrix = np.random.randint(1,20,(3,3))
view_slice = matrix[:2,:2]
print("Original matrix :")
print(matrix)
print("View Slice")
print(view_slice)
view_slice[0][0]=66
print("Updated View_slice ")
print(view_slice)
if np.array_equal(matrix[:2,:2],view_slice):
  print("modifying view_slice is  affecting matrix")
else:
  print("modifying view_slice is not affecting matrix")


Original matrix :
[[ 7 10 18]
 [18 16  7]
 [ 5  7 13]]
View Slice
[[ 7 10]
 [18 16]]
Updated View_slice 
[[66 10]
 [18 16]]
modifying view_slice is  affecting matrix


In [70]:
# 78.Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

array_a = np.arange(1,13).reshape(4,3)
view_b = array_a[:2,:2]
print("Original array_a :")
print(array_a)
print("View_b")
print(view_b)
view_b+=5
print("Updated View_b ")
print(view_slice)
if np.array_equal(array_a[:2,:2],view_b):
  print("modifying view_b is affecting array_a")
else:
  print("modifying view_b is not affecting array_a")


Original array_a :
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
View_b
[[1 2]
 [4 5]]
Updated View_b 
[[66 10]
 [18 16]]
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]
modifying view_b is affecting array_a


In [75]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
# reflects changes in the original `orig_array`.
orig_array = np.arange(1,9).reshape(2,4)
reshaped_view = orig_array.reshape(4,2)

print("Original Array :")
print(orig_array)
reshaped_view+=6
print("Updated reshaped array :")
print(reshaped_view)
print(orig_array)
if np.array_equal(orig_array,reshaped_view):
  print("modifying reshaped_view is affecting orig_array")
else:
  print("modifying reshaped_view is not affecting orig_array")



Original Array :
[[1 2 3 4]
 [5 6 7 8]]
Updated reshaped array :
[[ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]
[[ 7  8  9 10]
 [11 12 13 14]]
modifying reshaped_view is not affecting orig_array


In [76]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`

data = np.random.randint(1,20,(3,4))
data_copy = data[data>5]
print(data)
print(data_copy)
data_copy[0] =100
print("Modified data_copy :",data_copy)
if np.array_equal(data_copy,data):
  print("Affects data")
else:
  print("Does not affects data")

[[ 4 17  1 16]
 [ 4  2 14 19]
 [ 3  3 10  4]]
[17 16 14 19 10]
Modified data_copy : [100  16  14  19  10]
Does not affects data


In [80]:
# 81.Create two matrices A and B of identical shape containing integers and perform addition and subtraction
# operations between them.
A = np.random.randint(1,20,(3,3))
B = np.random.randint(1,20,(3,3))
print("A:")
print(A)
print("B:")
print(B)
print("Addition :")
print(np.add(A,B))
print("Subraction :")
print(np.subtract(A,B))


A:
[[ 9  2  4]
 [ 3  3 10]
 [19  9 12]]
B:
[[14 13  1]
 [11 19  5]
 [ 9  6 10]]
Addition :
[[23 15  5]
 [14 22 15]
 [28 15 22]]
Subraction :
[[ -5 -11   3]
 [ -8 -16   5]
 [ 10   3   2]]


In [82]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
C = np.random.randint(1,20,(3,2))
D = np.random.randint(1,20,(2,4))
print("C :")
print(C)
print("D :")
print(D)
print("Multipliaction :")
print(np.dot(C,D))

C :
[[19 19]
 [17 15]
 [ 7  1]]
D :
[[11 10 18 11]
 [ 4 16  4  9]]
Multipliaction :
[[285 494 418 380]
 [247 410 366 322]
 [ 81  86 130  86]]


In [84]:
# 83.Create a matrix `E` and find its transpose.
E = np.random.randint(1,15,(2,4))
print("E :")
print(E)
print("Transpose of E :")
print(E.T)

E :
[[ 7 13  9  6]
 [ 9  9  9 13]]
Transpose of E :
[[ 7  9]
 [13  9]
 [ 9  9]
 [ 6 13]]


In [86]:
# 84. Generate a square matrix `F` and compute its determinant.
F = np.random.randint(1,10,(3,3))
print("F :")
print(F)
print("Determent of F :")
print(np.linalg.det(F))

F :
[[4 4 7]
 [9 8 3]
 [5 8 2]]
Determent of F :
180.0


In [87]:
# 85.  Create a square matrix `G` and find its inverse
G = np.random.randint(1,10,(3,3))
print("G :")
print(G)
print("Inverse of G")
print(np.linalg.inv(G))

G :
[[7 1 3]
 [8 7 9]
 [3 7 8]]
Inverse of G
[[-0.36842105  0.68421053 -0.63157895]
 [-1.94736842  2.47368421 -2.05263158]
 [ 1.84210526 -2.42105263  2.15789474]]
